#!/usr/bin/env Rscript
# Deploy curated shinyglass demos to shinyapps.io.
#
# Prerequisites (one-time on your machine — do not commit secrets):
#   install.packages(c("rsconnect", "remotes"))
#   rsconnect::setAccountInfo(
#     name   = "<account>",
#     token  = "<token>",
#     secret = "<secret>"
#   )
#   # shinyglass MUST be installed from GitHub (not a local path) so renv can
#   # snapshot it:
#   remotes::install_github("ericrayanderson/shinyglass", upgrade = "never")
#
# Usage (from package root):
#   Rscript inst/scripts/deploy-shinyapps-demos.R
#   Rscript inst/scripts/deploy-shinyapps-demos.R --apps=demo,dashboard
#   Rscript inst/scripts/deploy-shinyapps-demos.R --account=myaccount --dry-run
#
# After deploy, paste the printed URLs into README.md "Live demos".

args <- commandArgs(trailingOnly = TRUE)

get_flag <- function(flag, default = NULL) {
  hit <- grep(paste0("^", flag, "="), args, value = TRUE)
  if (!length(hit)) {
    return(default)
  }
  sub(paste0("^", flag, "="), "", hit[[1]])
}

has_flag <- function(flag) any(args == flag)

dry_run <- has_flag("--dry-run")
account <- get_flag("--account", NULL)
apps_arg <- get_flag("--apps", "demo,dashboard,intensity,inputs,olympics,plotly_gt")
app_keys <- trimws(strsplit(apps_arg, ",", fixed = TRUE)[[1]])

if (!requireNamespace("rsconnect", quietly = TRUE)) {
  stop('Install rsconnect first: install.packages("rsconnect")', call. = FALSE)
}

script_path <- sub(
  "^--file=",
  "",
  grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)[1]
)
if (!is.na(script_path) && nzchar(script_path)) {
  pkg_root <- normalizePath(file.path(dirname(script_path), "..", ".."), winslash = "/")
} else {
  pkg_root <- normalizePath(".", winslash = "/")
}

# Fail fast if shinyglass is a local-path install (renv cannot snapshot those).
sg_desc <- utils::packageDescription("shinyglass")
if (is.list(sg_desc)) {
  remote_type <- sg_desc$RemoteType
  if (is.null(remote_type) || !remote_type %in% c("github", "gitlab", "bitbucket", "url", "standard")) {
    # CRAN install has no RemoteType — OK. Local/path installs often have
    # RemoteType "local" or empty with RemoteUrl file://
    if (identical(remote_type, "local") ||
      grepl("^file:", sg_desc$RemoteUrl %||% "")) {
      stop(
        "shinyglass is installed from a local path; renv cannot snapshot it.\n",
        "Reinstall from GitHub first:\n",
        "  remotes::install_github(\"ericrayanderson/shinyglass\", upgrade = \"never\", force = TRUE)",
        call. = FALSE
      )
    }
  }
}

catalog <- list(
  demo = list(
    appName = "shinyglass-demo",
    source = file.path(pkg_root, "inst", "examples", "demo-app.R"),
    kind = "single",
    imports = c("shiny", "bslib", "ggplot2", "shinyglass")
  ),
  dashboard = list(
    appName = "shinyglass-dashboard",
    source = file.path(pkg_root, "inst", "examples", "bslib-dashboard.R"),
    kind = "single",
    imports = c("shiny", "bslib", "ggplot2", "DT", "shinyglass")
  ),
  intensity = list(
    appName = "shinyglass-intensity",
    source = file.path(pkg_root, "inst", "examples", "intensity-slider-demo.R"),
    kind = "single",
    imports = c("shiny", "bslib", "ggplot2", "shinyglass")
  ),
  inputs = list(
    appName = "shinyglass-inputs",
    source = file.path(pkg_root, "inst", "examples", "inputs-gallery.R"),
    kind = "single",
    imports = c("shiny", "bslib", "shinyglass")
  ),
  olympics = list(
    appName = "shinyglass-olympics",
    source = file.path(pkg_root, "inst", "shinyapps", "olympic-medals"),
    kind = "dreamrs",
    entry = "app-glass.R",
    imports = c(
      "shiny", "shinyWidgets", "ggplot2", "ggthemes", "bslib", "dplyr",
      "data.table", "reactable", "tidyr", "ggtext", "shinyglass"
    )
  ),
  plotly_gt = list(
    appName = "shinyglass-plotly-gt",
    source = file.path(pkg_root, "inst", "examples", "plotly-gt-demo.R"),
    kind = "single",
    imports = c("shiny", "bslib", "plotly", "gt", "waiter", "shinyglass")
  )
)

unknown <- setdiff(app_keys, names(catalog))
if (length(unknown)) {
  stop(
    "Unknown apps: ", paste(unknown, collapse = ", "),
    "\nChoose from: ", paste(names(catalog), collapse = ", "),
    call. = FALSE
  )
}

write_demo_description <- function(app_dir, imports) {
  writeLines(
    c(
      "Package: shinyglassdemo",
      "Title: shinyglass demo",
      "Version: 0.0.0.9000",
      paste0("Imports: ", paste(imports, collapse = ", ")),
      "Remotes: github::ericrayanderson/shinyglass"
    ),
    file.path(app_dir, "DESCRIPTION")
  )
}

stage_single <- function(src_file, app_dir, imports) {
  if (!file.exists(src_file)) {
    stop("Missing example: ", src_file, call. = FALSE)
  }
  if (dir.exists(app_dir)) {
    unlink(app_dir, recursive = TRUE)
  }
  dir.create(app_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(
    c(
      "# Generated by deploy-shinyapps-demos.R — do not edit by hand",
      readLines(src_file, warn = FALSE)
    ),
    file.path(app_dir, "app.R")
  )
  write_demo_description(app_dir, imports)
}

stage_dreamrs <- function(app_src, entry, app_dir, imports) {
  if (!dir.exists(app_src)) {
    stop(
      "Missing dreamRs app dir: ", app_src,
      "\nVendored under inst/shinyapps (not in CRAN tarball).",
      call. = FALSE
    )
  }
  if (dir.exists(app_dir)) {
    unlink(app_dir, recursive = TRUE)
  }
  dir.create(dirname(app_dir), recursive = TRUE, showWarnings = FALSE)
  file.copy(app_src, dirname(app_dir), recursive = TRUE)
  copied <- file.path(dirname(app_dir), basename(app_src))
  if (!identical(normalizePath(copied), normalizePath(app_dir, mustWork = FALSE))) {
    if (dir.exists(app_dir)) {
      unlink(app_dir, recursive = TRUE)
    }
    file.rename(copied, app_dir)
  }
  entry_path <- file.path(app_dir, entry)
  if (!file.exists(entry_path)) {
    stop("Missing entry ", entry, " in ", app_dir, call. = FALSE)
  }
  file.copy(entry_path, file.path(app_dir, "app.R"), overwrite = TRUE)
  write_demo_description(app_dir, imports)
}

`%||%` <- function(x, y) if (is.null(x) || !length(x) || (is.character(x) && !nzchar(x[[1]]))) y else x

staging <- file.path(tempdir(), "shinyglass-deploy")
dir.create(staging, showWarnings = FALSE, recursive = TRUE)

urls <- character()
for (key in app_keys) {
  spec <- catalog[[key]]
  app_dir <- file.path(staging, spec$appName)
  message("Staging ", spec$appName, " …")
  imports <- spec$imports %||% c("shiny", "bslib", "shinyglass")
  if (identical(spec$kind, "single")) {
    stage_single(spec$source, app_dir, imports)
  } else {
    stage_dreamrs(spec$source, spec$entry, app_dir, imports)
  }

  if (dry_run) {
    message("[dry-run] would deployApp(", app_dir, ", appName = ", spec$appName, ")")
    next
  }

  deploy_args <- list(
    appDir = app_dir,
    appName = spec$appName,
    forceUpdate = TRUE,
    lint = FALSE,
    launch.browser = FALSE,
    # Anyone with the URL can view (not account-only).
    appVisibility = "public"
  )
  if (!is.null(account) && nzchar(account)) {
    deploy_args$account <- account
  }

  message("Deploying ", spec$appName, " …")
  do.call(rsconnect::deployApp, deploy_args)

  acct <- account
  if (is.null(acct) || !nzchar(acct)) {
    accts <- tryCatch(rsconnect::accounts(), error = function(e) NULL)
    if (!is.null(accts) && nrow(accts)) {
      acct <- accts$name[[1]]
    }
  }
  if (is.null(acct) || !nzchar(acct)) {
    acct <- "<account>"
  }
  url <- sprintf("https://%s.shinyapps.io/%s/", acct, spec$appName)
  urls <- c(urls, sprintf("- [%s](%s)", spec$appName, url))
  message("  → ", url)
}

if (length(urls)) {
  message("\n## Live demos (paste into README)\n")
  message(paste(urls, collapse = "\n"))
}

message("\nDone.")
