#!/usr/bin/env Rscript
# Deploy curated shinyglass demos to shinyapps.io.
#
# Prerequisites (one-time on your machine — do not commit secrets):
#   install.packages("rsconnect")
#   rsconnect::setAccountInfo(
#     name   = "<account>",
#     token  = "<token>",
#     secret = "<secret>"
#   )
#
# Usage (from package root):
#   Rscript inst/scripts/deploy-shinyapps-demos.R
#   Rscript inst/scripts/deploy-shinyapps-demos.R --apps=demo,dashboard
#   Rscript inst/scripts/deploy-shinyapps-demos.R --account=myaccount --dry-run
#
# After deploy, paste the printed URLs into README.md "Live demos".

args <- commandArgs(trailingOnly = TRUE)

get_flag <- function(flag, default = NULL) {
  hit <- grep(paste0("^", flag, "="), args, value = TRUE)
  if (!length(hit)) {
    return(default)
  }
  sub(paste0("^", flag, "="), "", hit[[1]])
}

has_flag <- function(flag) any(args == flag)

dry_run <- has_flag("--dry-run")
account <- get_flag("--account", NULL)
apps_arg <- get_flag("--apps", "demo,dashboard,inputs,olympics")
app_keys <- trimws(strsplit(apps_arg, ",", fixed = TRUE)[[1]])

if (!requireNamespace("rsconnect", quietly = TRUE)) {
  stop('Install rsconnect first: install.packages("rsconnect")', call. = FALSE)
}

script_path <- sub(
  "^--file=",
  "",
  grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)[1]
)
if (!is.na(script_path) && nzchar(script_path)) {
  pkg_root <- normalizePath(file.path(dirname(script_path), "..", ".."), winslash = "/")
} else {
  pkg_root <- normalizePath(".", winslash = "/")
}

catalog <- list(
  demo = list(
    appName = "shinyglass-demo",
    source = file.path(pkg_root, "inst", "examples", "demo-app.R"),
    kind = "single",
    imports = c("shiny", "bslib", "ggplot2", "shinyglass")
  ),
  dashboard = list(
    appName = "shinyglass-dashboard",
    source = file.path(pkg_root, "inst", "examples", "bslib-dashboard.R"),
    kind = "single",
    imports = c("shiny", "bslib", "ggplot2", "DT", "shinyglass")
  ),
  inputs = list(
    appName = "shinyglass-inputs",
    source = file.path(pkg_root, "inst", "examples", "inputs-gallery.R"),
    kind = "single",
    imports = c("shiny", "bslib", "shinyglass")
  ),
  olympics = list(
    appName = "shinyglass-olympics",
    source = file.path(pkg_root, "inst", "shinyapps", "olympic-medals"),
    kind = "dreamrs",
    entry = "app-glass.R"
  )
)

unknown <- setdiff(app_keys, names(catalog))
if (length(unknown)) {
  stop(
    "Unknown apps: ", paste(unknown, collapse = ", "),
    "\nChoose from: ", paste(names(catalog), collapse = ", "),
    call. = FALSE
  )
}

# Copy local shinyglass source so uncommitted/dev APIs deploy (not CRAN/GitHub).
vendor_shinyglass <- function(app_dir) {
  dest <- file.path(app_dir, "shinyglass")
  if (dir.exists(dest)) {
    unlink(dest, recursive = TRUE)
  }
  dir.create(dest, recursive = TRUE, showWarnings = FALSE)
  for (part in c("DESCRIPTION", "NAMESPACE", "R", "inst")) {
    src <- file.path(pkg_root, part)
    if (!file.exists(src)) {
      stop("Missing package part for vendoring: ", src, call. = FALSE)
    }
    if (file.info(src)$isdir) {
      file.copy(src, dest, recursive = TRUE)
    } else {
      file.copy(src, file.path(dest, part))
    }
  }
  # Drop heavy non-runtime trees that may exist under inst/
  for (drop in c(
    file.path(dest, "inst", "shinyapps"),
    file.path(dest, "inst", "scripts"),
    file.path(dest, "inst", "examples")
  )) {
    if (dir.exists(drop)) {
      unlink(drop, recursive = TRUE)
    }
  }
  dest
}

stage_single <- function(src_file, app_dir, imports = c("shiny", "bslib", "ggplot2", "shinyglass")) {
  if (!file.exists(src_file)) {
    stop("Missing example: ", src_file, call. = FALSE)
  }
  if (dir.exists(app_dir)) {
    unlink(app_dir, recursive = TRUE)
  }
  dir.create(app_dir, recursive = TRUE, showWarnings = FALSE)
  writeLines(
    c(
      "# Generated by deploy-shinyapps-demos.R — do not edit by hand",
      readLines(src_file, warn = FALSE)
    ),
    file.path(app_dir, "app.R")
  )
  vendor_shinyglass(app_dir)
  writeLines(
    c(
      "Package: shinyglassdemo",
      "Title: shinyglass demo",
      "Version: 0.0.0.9000",
      paste0("Imports: ", paste(imports, collapse = ", ")),
      "Remotes: local::./shinyglass"
    ),
    file.path(app_dir, "DESCRIPTION")
  )
}

stage_dreamrs <- function(app_src, entry, app_dir) {
  if (!dir.exists(app_src)) {
    stop(
      "Missing dreamRs app dir: ", app_src,
      "\nVendored under inst/shinyapps (not in CRAN tarball).",
      call. = FALSE
    )
  }
  if (dir.exists(app_dir)) {
    unlink(app_dir, recursive = TRUE)
  }
  dir.create(dirname(app_dir), recursive = TRUE, showWarnings = FALSE)
  file.copy(app_src, dirname(app_dir), recursive = TRUE)
  copied <- file.path(dirname(app_dir), basename(app_src))
  if (!identical(normalizePath(copied), normalizePath(app_dir, mustWork = FALSE))) {
    if (dir.exists(app_dir)) {
      unlink(app_dir, recursive = TRUE)
    }
    file.rename(copied, app_dir)
  }
  entry_path <- file.path(app_dir, entry)
  if (!file.exists(entry_path)) {
    stop("Missing entry ", entry, " in ", app_dir, call. = FALSE)
  }
  file.copy(entry_path, file.path(app_dir, "app.R"), overwrite = TRUE)
  vendor_shinyglass(app_dir)
  writeLines(
    c(
      "Package: shinyglassolympics",
      "Title: shinyglass olympics demo",
      "Version: 0.0.0.9000",
      paste0(
        "Imports: shiny, bslib, ggplot2, shinyWidgets, reactable, dplyr, ",
        "data.table, tidyr, ggtext, ggthemes, shinyglass"
      ),
      "Remotes: local::./shinyglass"
    ),
    file.path(app_dir, "DESCRIPTION")
  )
}

staging <- file.path(tempdir(), "shinyglass-deploy")
dir.create(staging, showWarnings = FALSE, recursive = TRUE)

urls <- character()
for (key in app_keys) {
  spec <- catalog[[key]]
  app_dir <- file.path(staging, spec$appName)
  message("Staging ", spec$appName, " …")
  if (identical(spec$kind, "single")) {
    stage_single(spec$source, app_dir, imports = spec$imports)
  } else {
    stage_dreamrs(spec$source, spec$entry, app_dir)
  }

  if (dry_run) {
    message("[dry-run] would deployApp(", app_dir, ", appName = ", spec$appName, ")")
    next
  }

  deploy_args <- list(
    appDir = app_dir,
    appName = spec$appName,
    forceUpdate = TRUE,
    lint = FALSE,
    launch.browser = FALSE
  )
  if (!is.null(account) && nzchar(account)) {
    deploy_args$account <- account
  }

  message("Deploying ", spec$appName, " …")
  do.call(rsconnect::deployApp, deploy_args)

  acct <- account
  if (is.null(acct) || !nzchar(acct)) {
    accts <- tryCatch(rsconnect::accounts(), error = function(e) NULL)
    if (!is.null(accts) && nrow(accts)) {
      acct <- accts$name[[1]]
    }
  }
  if (is.null(acct) || !nzchar(acct)) {
    acct <- "<account>"
  }
  url <- sprintf("https://%s.shinyapps.io/%s/", acct, spec$appName)
  urls <- c(urls, sprintf("- [%s](%s)", spec$appName, url))
  message("  → ", url)
}

if (length(urls)) {
  message("\n## Live demos (paste into README)\n")
  message(paste(urls, collapse = "\n"))
}

message("\nDone.")
